spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"
  cache:
    caffeine:
      spec: expireAfterWrite=1m

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE # Outgoing http requests
    org.springframework.jdbc.core: DEBUG # SQL

twitch:
  client-id: "YOUR TWITCH CLIENT ID"
  secret: "YOUR TWITCH CLIENT SECRET"
